### ISSUE TITLE
[sqd codegen] Invalid property Account.user: User.account is not @unique

### ISSUE THREAD

**Issue by minhnhat-dnt** [subsquid/docs#187]
I followed this guide https://docs.subsquid.io/basics/schema-file/entity-relations/#one-to-one-relations to create One-to-one relations. 
But I have an error when using `sqd codegen` : 

```
~/codegen-sample$ sqd codegen
CODEGEN
Error: Invalid property Account.user: User.account is not @unique
    at invalidProperty (/home/nhat/codegen-sample/node_modules/@subsquid/openreader/lib/model.tools.js:253:12)
    at validateLookups (/home/nhat/codegen-sample/node_modules/@subsquid/openreader/lib/model.tools.js:209:35)
    at validateModel (/home/nhat/codegen-sample/node_modules/@subsquid/openreader/lib/model.tools.js:127:5)
    at buildModel (/home/nhat/codegen-sample/node_modules/@subsquid/openreader/lib/model.schema.js:44:37)
    at loadModel (/home/nhat/codegen-sample/node_modules/@subsquid/openreader/lib/tools.js:56:42)
    at /home/nhat/codegen-sample/node_modules/@subsquid/typeorm-codegen/lib/main.js:23:39
    at runProgram (/home/nhat/codegen-sample/node_modules/@subsquid/util-internal/lib/misc.js:61:9)
    at Object.<anonymous> (/home/nhat/codegen-sample/node_modules/@subsquid/typeorm-codegen/lib/main.js:13:32)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
```

After making User.account property to be unique as below
![image](https://user-images.githubusercontent.com/121567737/230928044-82da482b-3626-409b-b2cf-bf94ccf9b92a.png)

The model account.model.ts in src/model/generated can't generate `account` column although User model has been imported
![image](https://user-images.githubusercontent.com/121567737/230928247-f5a1dd66-5273-47ef-b2c6-36569b50b358.png)

Do you have any ideas for these issues? 
Thanks

**Comment by abernatskiy** [comment]
It's a forgotten `@unique`, and there does seem to be an issue with the `Account` class from your second screenshot. `user` is a reverse lookup field within the `Account` entity, so it won't make a column in the database. However, it should still be defined in Typescript in order to make reverse lookups available in the processor code.

Good catch. I'll fix the docs within 24 hrs. Will see what can be done about codegen skipping the inverse lookups in the one-to-one case.

**Comment by okhaimie-dev** [comment]
This issue seems to have been solved.

@abernatskiy can you close it

**Comment by abernatskiy** [comment]
@okhaimie-dev Not yet, unfortunately: the docs are fixed, but I still need to get my fix for `@subsquid/typeorm-codegen` merged. Will leave a comment when done.

**Comment by abernatskiy** [comment]
Could not get the patch to `@subsquid/typeorm-codegen`, in part because there was never an explicit request from any users for this feature. If someone ever needs to have an inverse lookup field in TypeORM model code in a squid, please open another issue and mention this one in it.
